<head>
    <link rel="stylesheet" href="css/styleheader.css">
</head>
<html>
    <header>
        <nav>
            <h1><a href="/agenceimmo/index.php">Immobilier</a></h1>
            <div class="right">
                <p><a href="#">Acheter</a></p>
                <p><a class="btn-contact" href="#">Contact</a></p>
                <button class="btn-contact" onclick="window.location.href = '/agenceimmo/vuescontroleurs/formRechercheBien.php';">Chercher un Bien</button>
            </div>
        </nav>
    </header>
</html>
