    <header>
        <nav>
            <h1><a href="../index.html">Immobilier</a></h1>
            <div class="right">
                <p><a href="acheter/acheter-categories.html">Acheter</a></p>
                <p><a href="#">Vendre</a></p>
                <p><a href="#">Louer</a></p>
                <button onclick="window.location.href = 'vuesControleur/rechercheBiens.php';">Chercher un Bien</button>
            </div>
        </nav>
    </header>
