<head>
    <link rel="stylesheet" href="/agenceimmo/css/styleheader.css">
</head>
<html>
    <header>
        <nav>
            <h1><a href="index.html">Immobilier</a></h1>
            <div class="right">
                <p><a href="/agenceimmo/vuescontroleurs/acheter/acheter-categories.php">Acheter</a></p>
                <p><a class="btn-contact" href="/agenceimmo/vuescontroleurs/contact.php">Contact</a></p>
                <button class="btn-contact" onclick="window.location.href = '/agenceimmo/vuescontroleurs/formRechercheBien.php';">Chercher un Bien</button>
            </div>
        </nav>
    </header>
</html>
