<head>
    <link rel="stylesheet" href="/agenceimmo/css/stylefooter.css">
</head>
<html>
    <footer>
        <div class="column">
            <h3>Navigation</h3>
            <p><a href="/agenceimmo/index.php">Acceuil</a></p>
            <p><a class="btn-contact" href="#">Contact</a></p>
            <p><a class="btn-connexion" href="/agenceimmo/vuescontroleurs/login.php">Se connecter</a></p>
        </div>
    </footer>   
</html>
